version: "3.7"

services:

  nginx:
    build:
      context: ./docker/nginx
    volumes:
      - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./app:/var/www
      - ./docker/nginx/ssl:/etc/nginx/ssl
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - php-fpm
    networks:
      - "backend_network"

  php-fpm:
    build:
      context: ./docker/php-fpm
    volumes:
      - ./app:/var/www
    ports:
      - "9000:9000"
    depends_on:
      - postgres
    networks:
      - "backend_network"

  postgres:
    image: postgres:14.2
    environment:
      POSTGRES_DB: default
      POSTGRES_USER: default
      POSTGRES_PASSWORD: default
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./docker/postgres/data:/var/lib/postgresql/data/pgdata:rw
      - ./app:/var/www:ro
    networks:
      - "backend_network"

networks:
  backend_network:
    driver: bridge
